# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d90a26f50361e17b86d46a77d11062dc8b12596df6f666047124ce98716f39b2057d87fc27fb0edba9ba56e1e219804885193732cdc13c467647a52defd6a4

test:
  secret_key_base: bac7eee11b014eb9c68467fde58ef7d18fdb97e0e57eb60dfb3a4d8c51fd89c2ffdc268881b3eb6e551eecd6160e0bd912aa02681ac6eb43940c059c1e1fc59d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
